### PR TITLE
[Kinesis Video] Add File MediaSource Demo

### PR DESCRIPTION
**Pull request by sirknightj**
*Issue #, if available:*

*Description of changes:*
Add demo/example of using the File MediaSource. We create and configure the file mediasource, which is a mediasource backed by local image files, and send those frames over to AWS for ingestion. Consumers can [configure their file mediasource](https://github.com/sirknightj/aws-sdk-android-samples/blob/dab285be113a68daa2a72f03de52c1b4b679a2a6/AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/fragment/FramesFragment.java#L130) and place their files within the [Android Assets folder](https://github.com/sirknightj/aws-sdk-android-samples/tree/dab285be113a68daa2a72f03de52c1b4b679a2a6/AmazonKinesisVideoDemoApp/src/main/assets). This stream will continuously loop through all of the files in order, looping once it hits the end.

Note that in this PR, the [dependency for KVS](https://github.com/sirknightj/aws-sdk-android-samples/blob/dab285be113a68daa2a72f03de52c1b4b679a2a6/AmazonKinesisVideoDemoApp/build.gradle#L52) is set to [2.30.0](https://search.maven.org/artifact/com.amazonaws/aws-android-sdk-kinesisvideo), which has not yet been released. We are anticipating that the [File MediaSource changes within the SDK](https://github.com/aws-amplify/aws-sdk-android/pull/2596) will be released along with 2.30.0, which these changes rely on. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sirknightj** [comment]
Bumped to 2.31.0, since changes not released in 2.30

**Comment by disa6302** [comment]
File changes look good. Looks like there is a conflict?
Can we get those fixed?
Also, can we add a small section in the README giving instructions on how to run this demo?

**Review by unicornss — COMMENTED** [review]
this sample demonstrates how to use KVS Producer SDK (Android) to send frames from a file source to KVS cloud.

**Comment by sirknightj** [comment]
> File changes look good. Looks like there is a conflict?
Can we get those fixed?

Fixed in the Merge.

> Also, can we add a small section in the README giving instructions on how to run this demo?

Done.

**Review by unicornss — COMMENTED** [review]
looks good to me.

**Review by unicornss — APPROVED** [review]

**Review by sdhuka — APPROVED** [review]

**Review by unicornss — APPROVED** [review]

**Review by sdhuka — APPROVED** [review]

**Pull request merged**
